### ISSUE TITLE
If support for webp ?

### ISSUE THREAD

**Issue by markdashi** [Tencent/LKImageKit#10]
The kit can support for webp?

**Comment by kelingjie1** [comment]
support with plugin(LKImageWepbDecoder) like LKImageSystemDecoder. It is testing and will coming soon.

**Comment by MountainHill** [comment]
同问

**Comment by kelingjie1** [comment]
项目已经有插件支持了，测试后就开源出来

**Comment by markdashi** [comment]
I want to know the Kit can perfrom better than SDWebImage?

**Comment by MountainHill** [comment]
@kelingjie1  测试完成了吗？

**Comment by kelingjie1** [comment]
Done. We use a plugin(LKImageWebPDecoder) to decode webp include animated webp.
