### ISSUE TITLE
Remove MOV video file form project

### ISSUE THREAD

**Issue by CodeEagle** [Tencent/LKImageKit#12]
It's waste of network traffic. Can post to video platform and add link to it.

Also remove from history.

Everytime when integrate it, need to waste 25mb.

**Comment by santcool** [comment]
+10086

**Comment by AAChartModel** [comment]
+1

**Comment by kelingjie1** [comment]
done

**Comment by CodeEagle** [comment]
Hi @kelingjie1 
git history still holding the mov file.
You can use `BFG` or `git filter branch` to remove the mov data.
Or it's still got a 25mb position in `git objects`

**Comment by kelingjie1** [comment]
Done. Cool!
