### ISSUE TITLE
why clear LRUQueue first in [LKImageMemoryCache clearLastOne function]

### ISSUE THREAD

**Issue by zq54zquan** [Tencent/LKImageKit#15]
according the source code ,the items in FIFOQueue just been used once ,  i think its item should be deleted before the LRUQueue. right?

**Comment by kelingjie1** [comment]
Because FIFO is changing very fast. Image in FIFO may be used just a few seconds. LRU is more stable. The last image in LRU should be old. So we remove last one in LRU.
