### ISSUE TITLE
是否考虑加入图片压缩功能？

### ISSUE THREAD

**Issue by TheLittleBoy** [Tencent/LKImageKit#16]
从相册中选择的图片一般都比较大，为了方便图片传输，往往需要压缩一下。

**Comment by kelingjie1** [comment]
已经有的。显示和缓存的都是默认会缩放到显示区域的大小，不会额外占用太多内存的。

**Comment by TheLittleBoy** [comment]
OK，有一份帮助文档就再好不过了。 另外，注释太少了。。。
