### ISSUE TITLE
如何加载工程里的gif

### ISSUE THREAD

**Issue by peterios2016** [Tencent/LKImageKit#23]
我看到你们的demo里有个test.gif，但是没有用到？

**Comment by kelingjie1** [comment]
发现确实没有，我删掉

**Comment by peterios2016** [comment]
那如何加载呢，还是说你们不提供加载工程里的gif这个功能

**Comment by kelingjie1** [comment]
可以加载，直接把地址设置到URL字段里就好了。原来的样例用的是GIF的，后来换webp了
