### ISSUE TITLE
有参数的URL请求失效问题

### ISSUE THREAD

**Issue by iostang** [Tencent/LKImageKit#25]
LKImage 5.3.1

LKImageNetworkFileLoaderTask

- (void)dataWithRequest:(LKImageRequest *)request callback:(LKImageDataCallback)callback

URL                       = [URL stringByAppendingString:@"?tp=sharp"];

这里有对URL进行拼接 会导致如果该图片的URL本身就是带参数的 拼接后就出错了

比如: 
http://qn-hunter-photo.fishtrip.cn/o_1bfu583ba1qg51ev61cdi1imvilg0.png-medium2?e=1525848700&token=nMq5NmyPkrs9m3DNnIQwz9UYNL7RZjfFiTpCZ851:Rjz0f5vTfU27edqjnPYj7ByJ15U=

拼上之后变成：
http://qn-hunter-photo.fishtrip.cn/o_1bfu583ba1qg51ev61cdi1imvilg0.png-medium2?e=1525848700&token=nMq5NmyPkrs9m3DNnIQwz9UYNL7RZjfFiTpCZ851:Rjz0f5vTfU27edqjnPYj7ByJ15U=?tp=sharp

看是否能改成这样：
if ([URL rangeOfString:@"?"].location == NSNotFound) {
        URL  = [URL stringByAppendingString:@"?tp=sharp"];
} else {
        URL   = [URL stringByAppendingString:@"&tp=sharp"];
}
或者不要这一行代码 单独出个插件处理tp=sharp

**Comment by kelingjie1** [comment]
不小心把业务代码带出来了。。。。确实应该删掉

**Comment by iostang** [comment]
大神  pod上还是旧代码 麻烦有空也升级一下 谢谢！😅
