### ISSUE TITLE
pod 安装后运行报错

### ISSUE THREAD

**Issue by Hanchunlin** [Tencent/LKImageKit#32]
NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator delete(void*)", referenced from:
      -[LKImageMemoryCache clear] in libLKImageKit.a(LKImageMemoryCache.o)
      -[LKImageMemoryCache deleteCache:] in libLKImageKit.a(LKImageMemoryCache.o)
      std::__1::list<ImageNode*, std::__1::allocator<ImageNode*> >::erase(std::__1::__list_const_iterator<ImageNode*, void*>) in libLKImageKit.a(LKImageMemoryCache.o)
      -[LKImageMemoryCache clearLastOneInLRU] in libLKImageKit.a(LKImageMemoryCache.o)
      std::__1::list<ImageNode*, std::__1::allocator<ImageNode*> >::pop_front() in libLKImageKit.a(LKImageMemoryCache.o)
      -[LKImageMemoryCache clearLastOneInFIFO] in libLKImageKit.a(LKImageMemoryCache.o)
      -[LKImageMemoryCache cacheImage:URL:] in libLKImageKit.a(LKImageMemoryCache.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kelingjie1** [comment]
看起来有点像是C++编译选项导致的问题，C++的编译选项是否有调整过呢

**Comment by kelingjie1** [comment]
样例工程如果编译没问题的话，可以考虑直接参考样例工程的设置。
C++的编译问题也可以直接读源代码google尝试解决一下，我这并没有办法重现
