### ISSUE TITLE
LKImageView LKImageScaleModeAspectFit的一个疑问

### ISSUE THREAD

**Issue by tianyewai** [Tencent/LKImageKit#33]
当设置LKImageView 的 scaleModel为LKImageScaleModeAspectFit时，图像区域外的部分一直是黑色，没办法设置吗？

**Comment by kelingjie1** [comment]
可以设置的，预绘制模式会保证输出的图片大小和规定大小一致，因此会有黑边。关闭预绘制之后，用的是UI调整的方式，就不会有黑边了。
