### ISSUE TITLE
建议提供性能方面的评测

### ISSUE THREAD

**Issue by dustturtle** [Tencent/LKImageKit#4]
和主流（包括系统实现）通过用例进行评测，并对结果（性能优劣）进行实现层面的解释

**Comment by kelingjie1** [comment]
https://github.com/Tencent/LKImageKit/issues/5
可以在这个issue下讨论，这里我也写了很多优化点。
之前写了一篇文章https://zhuanlan.zhihu.com/p/26955368可以先看看
后面还有更多的优化点没写进来，我会再输出一篇
