### ISSUE TITLE
为什么LKImageview继承UIView而不是继承UIImageview

### ISSUE THREAD

**Issue by helinyu** [Tencent/LKImageKit#7]
![image](https://user-images.githubusercontent.com/6794638/36839408-fb70bbfe-1d7c-11e8-9865-c2f96ecae907.png)

**Comment by helinyu** [comment]
发现这样多出了一个View

**Comment by helinyu** [comment]
这样冗余一个View会不会影响性能？

**Comment by kelingjie1** [comment]
结论是几乎不会影响。
至于为什么需要嵌套一个，这是由于要支持各种各样的缩放和裁剪模式。相对于功能性的提升，这里很小的额外性能开销是可以放弃的。
而且对于滑动流畅性来说，这里的开销只是一个零头。
